{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72b51e00-5297-4d3e-b2f5-2263837d6b47",
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.support.ui import WebDriverWait\n",
    "from selenium.webdriver.support import expected_conditions as EC\n",
    "import os\n",
    "import smtplib\n",
    "from email.mime.text import MIMEText\n",
    "\n",
    "KASPI_URL = \"https://kaspi.kz/shop/p/ehrmann-puding-vanil-bezlaktoznyi-1-5-200-g-102110634/?c=750000000\"\n",
    "CHECK_INTERVAL = 5 * 60  # проверка каждые 5 минут\n",
    "\n",
    "EMAIL_FROM = os.getenv(\"EMAIL_FROM\")\n",
    "EMAIL_TO = os.getenv(\"EMAIL_TO\")\n",
    "EMAIL_PASSWORD = os.getenv(\"EMAIL_PASSWORD\")  # app password for gmail\n",
    "\n",
    "def send_email(subject, body):\n",
    "    if not EMAIL_FROM or not EMAIL_TO or not EMAIL_PASSWORD:\n",
    "        print(\"Email settings not configured.\")\n",
    "        return\n",
    "\n",
    "    msg = MIMEText(body, \"plain\", \"utf-8\")\n",
    "    msg[\"Subject\"] = subject\n",
    "    msg[\"From\"] = EMAIL_FROM\n",
    "    msg[\"To\"] = EMAIL_TO\n",
    "\n",
    "    server = smtplib.SMTP_SSL(\"smtp.gmail.com\", 465)\n",
    "    server.login(EMAIL_FROM, EMAIL_PASSWORD)\n",
    "    server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())\n",
    "    server.quit()\n",
    "\n",
    "def check_availability():\n",
    "    options = Options()\n",
    "    options.add_argument(\"--headless\")\n",
    "    options.add_argument(\"--disable-gpu\")\n",
    "    options.add_argument(\"--no-sandbox\")\n",
    "\n",
    "    driver = webdriver.Chrome(options=options)\n",
    "    driver.get(KASPI_URL)\n",
    "\n",
    "    try:\n",
    "        availability_elem = WebDriverWait(driver, 10).until(\n",
    "            EC.presence_of_element_located(\n",
    "                (By.XPATH, '//div[contains(@class,\"product-availability__text\")]')\n",
    "            )\n",
    "        )\n",
    "        availability_text = availability_elem.text.lower()\n",
    "        driver.quit()\n",
    "        return \"в наличии\" in availability_text\n",
    "    except Exception as e:\n",
    "        print(\"Ошибка поиска наличия:\", e)\n",
    "        driver.quit()\n",
    "        return False\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    last_status = None  # None, True или False\n",
    "\n",
    "    while True:\n",
    "        in_stock = check_availability()\n",
    "        print(f\"Текущее наличие: {'в наличии' if in_stock else 'нет в наличии'}\")\n",
    "\n",
    "        # Отправляем email только если статус изменился\n",
    "        if last_status is None or in_stock != last_status:\n",
    "            if in_stock:\n",
    "                subject = \"Товар появился на Kaspi!\"\n",
    "                body = f\"🎉 Товар появился в наличии!\\n{KASPI_URL}\"\n",
    "                send_email(subject, body)\n",
    "            last_status = in_stock\n",
    "\n",
    "        time.sleep(CHECK_INTERVAL)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
